program: tune.py
name: corrected_sweep
project: DA6401
entity: jayagowtham-indian-institute-of-technology-madras
method: bayes
metric:
  goal: maximize
  name: val_acc
parameters:
  num_layers:
    values: [3,5,7]
  hidden_size:
    values: [32,64,128]
  weight_decay:
    values: [0,5e-4,5e-1]
  learning_rate:
    values: [1e-3, 1e-4]
  batch_size:
    values: [16, 32, 64]
  beta:
    values: [0.9]
  beta1:
    values: [0.9]
  beta2:
    values: [0.99]
  epsilon:
    values: [1e-6]
  epochs:
    values: [5,10]
  activation:
    values: ["tanh", "sigmoid", "ReLU"]
  weight_init:
    values: ["random", "Xavier"]
  optimizer:
    values: ["sgd", "momentum", "nag","rmsprop","adam","nadam"]

# Ensure it runs using your virtual environment
command:
  - dl_env\Scripts\python.exe
  - ${program}  


