program: tune.py
name: hp_tune_sweep_fine_recent
project: DA6401
entity: jayagowtham-indian-institute-of-technology-madras
method: bayes
metric:
  goal: maximize
  name: val_acc
parameters:
  num_layers:
    values: [3,4,5,6]
  hidden_size:
    values: [128,256,512]
  weight_decay:
    values: [0,5e-4]
  learning_rate:
    values: [1e-3, 1e-2]
  batch_size:
    values: [64,128]
  beta:
    values: [0.9]
  beta1:
    values: [0.9]
  beta2:
    values: [0.99]
  epsilon:
    values: [1e-6]
  epochs:
    values: [10,15,20]
  activation:
    values: ["sigmoid", "ReLU"]
  weight_init:
    values: ["random"]
  optimizer:
    values: ["adam","nadam"]

# Ensure it runs using your virtual environment
command:
  - dl_env\Scripts\python.exe
  - ${program}  
  # - --learning_rate=${learning_rate}
  # - --momentum=${momentum}
  # - --batch_size=${batch_size}
  # - --epochs=${epochs}
  # - --activation=${activation}
  # - --optimizer=${optimizer}

