program: tune.py
name: corrected_sweep_grid
project: DA6401
entity: jayagowtham-indian-institute-of-technology-madras
method: grid
metric:
  goal: maximize
  name: val_acc
parameters:
  num_layers:
    values: [3,4,5]
  hidden_size:
    values: [512]
  weight_decay:
    values: [0,5e-4,5e-2]
  learning_rate:
    values: [1e-4]
  batch_size:
    values: [128]
  beta:
    values: [0.9]
  beta1:
    values: [0.9]
  beta2:
    values: [0.99]
  epsilon:
    values: [1e-6]
  epochs:
    values: [20,25,30]
  activation:
    values: ["tanh"]
  weight_init:
    values: ["Xavier"]
  optimizer:
    values: ["nadam"]

# Ensure it runs using your virtual environment
command:
  - dl_env\Scripts\python.exe
  - ${program}  


